services:
  app:
    build: .
    container_name: ecoshop_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:15
    container_name: ecoshop_postgres
    environment:
      POSTGRES_DB: ecoshop_db
      POSTGRES_USER: ecoshop_user
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecoshop_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "uuuu"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data_fresh:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data_fresh:
